"""
Unit & Integration Tests for DepthWizard V2 API
Validates:
1. Health endpoint
2. Valid standard image upload (JPEG/PNG)
3. Invalid image upload (corrupt bytes) -> HTTP 400
4. Image without geospatial metadata (STATE_B, relative depth, metric_depth_available=false)
5. Image with geospatial metadata (GeoTIFF, STATE_C, metric_depth_available=true, dsm_available=true)
6. Successful relative-depth processing
7. Successful metric-depth processing
8. DSM and 3D PLY artifact generation
9. JSON response contract schema verification
10. Artifact accessibility (download URLs)
11. Web 3D Viewer endpoint
"""

import io
import pytest
import numpy as np
from PIL import Image
from fastapi.testclient import TestClient

from api.app import app
from src.config import INPUT_DIR, DEPTHANYTHING_OUTPUT_DIR

client = TestClient(app)


@pytest.fixture
def sample_jpeg_bytes() -> bytes:
    """Generates a standard 256x256 RGB JPEG in memory."""
    img = Image.new("RGB", (256, 256), color=(120, 160, 200))
    buf = io.BytesIO()
    img.save(buf, format="JPEG")
    return buf.getvalue()


@pytest.fixture
def sample_png_bytes() -> bytes:
    """Generates a standard 256x256 RGB PNG in memory."""
    img = Image.new("RGB", (256, 256), color=(80, 140, 60))
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


@pytest.fixture
def sample_geotiff_bytes() -> bytes:
    """Reads the synthetic sample GeoTIFF generated by generate_sample_data.py."""
    geotiff_path = INPUT_DIR / "sample_terrain.tif"
    assert geotiff_path.exists(), "Sample GeoTIFF must exist. Run generate_sample_data.py first."
    with open(geotiff_path, "rb") as f:
        return f.read()


@pytest.fixture
def sample_depth_map_bytes() -> bytes:
    """Reads the synthetic DepthAnything sample depth map."""
    depth_path = DEPTHANYTHING_OUTPUT_DIR / "sample_depth_map.npy"
    assert depth_path.exists(), "Sample depth map must exist."
    with open(depth_path, "rb") as f:
        return f.read()


def test_1_health_endpoint():
    """1. Test health endpoint returns 200 with system info."""
    response = client.get("/api/v1/health")
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "healthy"
    assert data["api_version"] == "v1.0.0"
    assert "depth_model" in data
    assert "device" in data
    assert "JPEG" in data["supported_formats"]


def test_2_invalid_image_upload():
    """2. Test uploading corrupt/invalid file returns HTTP 400."""
    corrupt_bytes = b"This is not a valid image file content."
    response = client.post(
        "/api/v1/process",
        files={"file": ("corrupt.jpg", corrupt_bytes, "image/jpeg")}
    )
    assert response.status_code == 400
    assert "detail" in response.json()


def test_3_standard_image_without_geospatial(sample_jpeg_bytes):
    """
    3. Test standard JPEG upload without geospatial metadata.
    Must return STATE_B, relative_depth_available=True, metric_depth_available=False,
    georeferencing_available=False, dsm_available=False.
    """
    response = client.post(
        "/api/v1/process",
        files={"file": ("aerial_photo.jpg", sample_jpeg_bytes, "image/jpeg")},
        data={"modulation_weight": 0.35, "z_exaggeration": 1.0}
    )
    assert response.status_code == 200
    data = response.json()

    # Verify state and availability flags
    assert data["state"] == "STATE_B"
    assert data["relative_depth_available"] is True
    assert data["camera_model_available"] is True
    assert data["metric_depth_available"] is False
    assert data["georeferencing_available"] is False
    assert data["dsm_available"] is False
    assert data["validation_available"] is False

    # Verify metadata
    assert data["metadata"]["image_width"] == 256
    assert data["metadata"]["image_height"] == 256
    assert data["metadata"]["format"] == "JPG"
    assert data["metadata"]["geospatial"] is None

    # Verify camera
    assert data["camera"]["estimated"] is True
    assert data["camera"]["fx"] is not None
    assert data["camera"]["cx"] == 128.0

    # Verify calibration
    assert data["calibration"]["calibrated"] is False
    assert data["calibration"]["method"] == "none"

    # Verify artifacts
    assert "input_image" in data["artifacts"]
    assert "relative_depth" in data["artifacts"]
    assert "relative_depth_colored" in data["artifacts"]
    assert "3d_model" in data["artifacts"]
    assert "dsm" not in data["artifacts"]  # No DSM for uncalibrated image


def test_4_geotiff_with_dem_processing(sample_geotiff_bytes):
    """
    4. Test GeoTIFF DEM processing.
    Must return STATE_C, metric_depth_available=True, georeferencing_available=True,
    dsm_available=True, and generate DSM + 3D PLY model artifacts.
    """
    response = client.post(
        "/api/v1/process",
        files={"file": ("sample_terrain.tif", sample_geotiff_bytes, "image/tiff")},
        data={"modulation_weight": 0.35, "z_exaggeration": 1.5}
    )
    assert response.status_code == 200
    data = response.json()

    # Verify state and flags
    assert data["state"] == "STATE_C"
    assert data["relative_depth_available"] is True
    assert data["metric_depth_available"] is True
    assert data["georeferencing_available"] is True
    assert data["dsm_available"] is True

    # Verify geospatial metadata
    assert data["metadata"]["geospatial"] is not None
    assert "4326" in data["metadata"]["geospatial"]["crs"]
    assert data["metadata"]["geospatial"]["bounds"] is not None

    # Verify calibration
    assert data["calibration"]["calibrated"] is True
    assert data["calibration"]["method"] == "geotiff_dem_fusion"

    # Verify artifacts
    assert "input_image" in data["artifacts"]
    assert "relative_depth" in data["artifacts"]
    assert "dsm" in data["artifacts"]
    assert "3d_model" in data["artifacts"]


def test_5_custom_depth_map_upload(sample_geotiff_bytes, sample_depth_map_bytes):
    """
    5. Test uploading both image and pre-computed relative depth map.
    """
    response = client.post(
        "/api/v1/process",
        files={
            "file": ("sample_terrain.tif", sample_geotiff_bytes, "image/tiff"),
            "depth_file": ("custom_depth.npy", sample_depth_map_bytes, "application/octet-stream")
        },
        data={"modulation_weight": 0.40, "z_exaggeration": 2.0}
    )
    assert response.status_code == 200
    data = response.json()
    assert data["state"] == "STATE_C"
    assert any("custom depth map" in msg for msg in data["messages"])


def test_6_json_contract_keys_and_timings(sample_png_bytes):
    """
    6. Strict verification of all required top-level keys in JSON contract.
    """
    response = client.post(
        "/api/v1/process",
        files={"file": ("test.png", sample_png_bytes, "image/png")}
    )
    assert response.status_code == 200
    data = response.json()

    required_keys = [
        "request_id",
        "state",
        "relative_depth_available",
        "camera_model_available",
        "metric_depth_available",
        "georeferencing_available",
        "dsm_available",
        "validation_available",
        "model_name",
        "device_used",
        "total_time_ms",
        "timings_ms",
        "messages",
        "warnings",
        "metadata",
        "camera",
        "calibration",
        "validation",
        "artifacts"
    ]
    for key in required_keys:
        assert key in data, f"Missing required top-level key: {key}"

    # Verify timings structure
    timings = data["timings_ms"]
    for t_key in [
        "ingestion_ms",
        "metadata_extraction_ms",
        "depth_inference_ms",
        "camera_modeling_ms",
        "3d_reconstruction_ms",
        "metric_calibration_ms",
        "geospatial_and_dsm_ms"
    ]:
        assert t_key in timings, f"Missing timing key: {t_key}"
        assert isinstance(timings[t_key], (int, float))

    assert data["total_time_ms"] > 0


def test_7_artifact_accessibility(sample_jpeg_bytes):
    """
    7. Test downloading generated artifacts via the GET artifact endpoints.
    """
    proc_res = client.post(
        "/api/v1/process",
        files={"file": ("target.jpg", sample_jpeg_bytes, "image/jpeg")}
    )
    assert proc_res.status_code == 200
    data = proc_res.json()
    req_id = data["request_id"]
    artifacts = data["artifacts"]

    # Test downloading input image
    input_url = artifacts["input_image"]["download_url"]
    r_img = client.get(input_url)
    assert r_img.status_code == 200
    assert len(r_img.content) > 0

    # Test downloading relative depth npy array
    depth_url = artifacts["relative_depth"]["download_url"]
    r_depth = client.get(depth_url)
    assert r_depth.status_code == 200
    loaded_arr = np.load(io.BytesIO(r_depth.content))
    assert isinstance(loaded_arr, np.ndarray)
    assert loaded_arr.shape == (256, 256)

    # Test downloading 3D PLY mesh
    mesh_url = artifacts["3d_model"]["download_url"]
    r_mesh = client.get(mesh_url)
    assert r_mesh.status_code == 200
    assert r_mesh.content.startswith(b"ply") or b"element vertex" in r_mesh.content


def test_8_web_viewer_endpoint(sample_jpeg_bytes):
    """
    8. Test the web 3D viewer HTML endpoint.
    """
    proc_res = client.post(
        "/api/v1/process",
        files={"file": ("view_test.jpg", sample_jpeg_bytes, "image/jpeg")}
    )
    req_id = proc_res.json()["request_id"]

    viewer_res = client.get(f"/api/v1/viewer/{req_id}")
    assert viewer_res.status_code == 200
    assert "text/html" in viewer_res.headers["content-type"]
    assert "DepthWizard 3D" in viewer_res.text
    assert req_id in viewer_res.text


def test_9_nonexistent_artifact_404():
    """
    9. Test accessing nonexistent artifact returns 404.
    """
    res = client.get("/api/v1/artifacts/fake_request_id/nonexistent.ply")
    assert res.status_code == 404
