"""Point cloud export utilities for PLY, XYZ, and WebGL JSON formats."""

import struct
from pathlib import Path
from typing import Dict, Any, Optional
import numpy as np

from backend.models.geometry import PointCloud3D


class PointCloudIO:
    """Exporter and serializer for 3D point cloud data."""

    @classmethod
    def save_ply(
        cls,
        point_cloud: PointCloud3D,
        file_path: str,
        binary: bool = True,
    ) -> str:
        """Write PointCloud3D to a standard Stanford PLY file.

        Args:
            point_cloud: PointCloud3D instance.
            file_path: Destination file path.
            binary: Whether to write binary little-endian PLY (faster, smaller).

        Returns:
            Absolute path to written PLY file.
        """
        path = Path(file_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        pts = point_cloud.points
        colors = point_cloud.colors
        normals = point_cloud.normals
        n_points = len(pts)

        has_normals = normals is not None and len(normals) == n_points

        header_lines = [
            "ply",
            "format binary_little_endian 1.0" if binary else "format ascii 1.0",
            f"comment generated by DepthWizard Engine",
            f"comment units={point_cloud.units.value}",
            f"comment frame={point_cloud.coordinate_frame.value}",
            f"element vertex {n_points}",
            "property float x",
            "property float y",
            "property float z",
        ]

        if has_normals:
            header_lines.extend([
                "property float nx",
                "property float ny",
                "property float nz",
            ])

        header_lines.extend([
            "property uchar red",
            "property uchar green",
            "property uchar blue",
            "end_header\n",
        ])

        header = "\n".join(header_lines).encode("ascii")

        with open(path, "wb") as f:
            f.write(header)

            if binary:
                # Pack binary format: float32*3 [+ float32*3] + uint8*3
                if has_normals:
                    # Combined structured array
                    data_dtype = np.dtype([
                        ("x", "<f4"), ("y", "<f4"), ("z", "<f4"),
                        ("nx", "<f4"), ("ny", "<f4"), ("nz", "<f4"),
                        ("r", "u1"), ("g", "u1"), ("b", "u1"),
                    ])
                    record_arr = np.empty(n_points, dtype=data_dtype)
                    record_arr["x"] = pts[:, 0]
                    record_arr["y"] = pts[:, 1]
                    record_arr["z"] = pts[:, 2]
                    record_arr["nx"] = normals[:, 0]
                    record_arr["ny"] = normals[:, 1]
                    record_arr["nz"] = normals[:, 2]
                    record_arr["r"] = colors[:, 0]
                    record_arr["g"] = colors[:, 1]
                    record_arr["b"] = colors[:, 2]
                    f.write(record_arr.tobytes())
                else:
                    data_dtype = np.dtype([
                        ("x", "<f4"), ("y", "<f4"), ("z", "<f4"),
                        ("r", "u1"), ("g", "u1"), ("b", "u1"),
                    ])
                    record_arr = np.empty(n_points, dtype=data_dtype)
                    record_arr["x"] = pts[:, 0]
                    record_arr["y"] = pts[:, 1]
                    record_arr["z"] = pts[:, 2]
                    record_arr["r"] = colors[:, 0]
                    record_arr["g"] = colors[:, 1]
                    record_arr["b"] = colors[:, 2]
                    f.write(record_arr.tobytes())
            else:
                for i in range(n_points):
                    line = f"{pts[i, 0]:.4f} {pts[i, 1]:.4f} {pts[i, 2]:.4f} "
                    if has_normals:
                        line += f"{normals[i, 0]:.4f} {normals[i, 1]:.4f} {normals[i, 2]:.4f} "
                    line += f"{colors[i, 0]} {colors[i, 1]} {colors[i, 2]}\n"
                    f.write(line.encode("ascii"))

        return str(path.resolve())

    @classmethod
    def to_web_json(
        cls,
        point_cloud: PointCloud3D,
        max_points: int = 150_000,
    ) -> Dict[str, Any]:
        """Serialize subsampled point cloud for lightweight WebGL/Three.js viewers."""
        pts = point_cloud.points
        colors = point_cloud.colors
        n_points = len(pts)

        if n_points == 0:
            return {
                "point_count": 0,
                "positions": [],
                "colors": [],
                "units": point_cloud.units.value,
                "frame": point_cloud.coordinate_frame.value,
                "bounds": [0, 0, 0, 0, 0, 0],
            }

        if n_points > max_points:
            step = int(np.ceil(n_points / max_points))
            pts_sub = pts[::step]
            colors_sub = colors[::step]
        else:
            pts_sub = pts
            colors_sub = colors

        # Flattened lists for typed buffer arrays
        positions_flat = [round(float(v), 3) for v in pts_sub.flatten()]
        # Colors normalized to [0, 1]
        colors_flat = [round(float(c) / 255.0, 3) for c in colors_sub.flatten()]

        bounds = point_cloud.bounds_min + point_cloud.bounds_max

        return {
            "point_count": len(pts_sub),
            "positions": positions_flat,
            "colors": colors_flat,
            "units": point_cloud.units.value,
            "frame": point_cloud.coordinate_frame.value,
            "is_metric": point_cloud.is_metric,
            "bounds": bounds,
        }
